#version 440

layout (local_size_x = 32) in;

layout(push_constant) uniform ShaderConstants
{
	// Material and ray stuff...
	uint pOffset;
	uint pSize;
};

layout (std430, set = 0, binding = 0) readonly buffer SrcIndices
{
	uint sSrcIndices[];
};

layout (std430, set = 0, binding = 1) buffer DstIndices
{
	uint sDstIndices[];
};

void main()
{
	uint Position = gl_GlobalInvocationID.x;

	if(Position > pSize)
		return;

	sDstIndices[Position] = sSrcIndices[Position] + pOffset;
}
